### ISSUE TITLE
Feature `WHITESPACE`-preservation

### ISSUE THREAD

**Issue by florianb** [jedmao/editorconfig-ini#7]
I just opened this issue to understand the reasoning and the intended outcome of the `WHITESPACE`-preservation.

As far as i understand it should achieve the following features:

1. Allow in-place-editing of the INI-file without changing any (insignificant) whitespaces.
2. Allow reproduction of the source file.

### In-Place-Editing

Does in-place-editing exist anyways? Considering a project uses version control, any inline-change would be handled as a delete-add-operation, wouldn't it?
I see only two reasons for having this:

a. to preserve indentation and
b. to preserve any special `EOL`-characters.

In general i would expect a file-generator always produces a valid-file. Preserving any whitespaces would also raise the question how are mixed-whitespace cases are handled or different indentation-levels.

**Comment by jedmao** [comment]
The scenario is that a user has hand-typed a file. Maybe they indented it a certain way that was more readable to them? Maybe they have some pairs with spaces on either side of the equals sign and some that have no spaces at all?

Now they want to validate a file conforms to a certain style with [Prettier][], which can be run in validation mode with `prettier` or in a fix mode with `prettier --write`. We don't need to preserve whitespace in the `prettier --write` scenario, but we need to somehow enable [Prettier][] to at least validate rules against a dirty file w/o doing any sort of manual labor. They shouldn't have to dig into the original file contents to determine if a rule is being violated or not.

Ultimately, I want to provide an EditorConfig [parser for Prettier](https://prettier.io/docs/en/api.html#custom-parser-api).

[prettier]: https://prettier.io/

**Comment by florianb** [comment]
Ahhh... thanks.

**Comment by jedmao** [comment]
Dealing with whitespace tokens is definitely a pain point, so I'd be super interested in how to approach this differently. Maybe just remove whitespace tokens until somebody asks for it? Then tell them it's a nightmare 😂

**Comment by florianb** [comment]
:laughing: That would be great but i think i will find a way to solve it in an elegant way. This is just my first serious attempt to create a grammar and i am feeling like at the beginning of an interesting journey.
